asterisk:
  log_filename: /var/log/asterisk/full

ari-py:
  python3: true

wazo-agentd:
  python3: true
  bind:
    etc/wazo-agentd/config.yml: /etc/wazo-agentd/config.yml
  clean:
    - /usr/local/bin/wazo-agentd
    - /usr/local/bin/wazo-agentd-wait

wazo-agentd-cli:
  python3: true
  clean:
    - /usr/local/bin/wazo-agentd-cli

wazo-agentd-client:
  python2: true
  python3: true

wazo-agid:
  python2: true
  bind:
    etc/wazo-agid/config.yml: /etc/wazo-agid/config.yml
    bin/change-pass-vm: /usr/share/asterisk/bin/change-pass-vm
  clean:
    - /usr/local/bin/wazo-agid

wazo-amid:
  python3: true
  bind:
    etc/wazo-amid/config.yml: /etc/wazo-amid/config.yml
  clean:
    - /usr/local/bin/wazo-amid

wazo-asterisk-config:
  bind:
    etc/asterisk/ari.d/01-wazo.conf: /etc/asterisk/ari.d/01-wazo.conf
    etc/asterisk/cel.d/01-wazo.conf: /etc/asterisk/cel.d/01-wazo.conf
    etc/asterisk/manager.d/99-general.conf: /etc/asterisk/manager.d/99-general.conf

wazo-auth:
  python3: true
  bind:
    alembic: /usr/share/wazo-auth/alembic
    etc/wazo-auth/config.yml: /etc/wazo-auth/config.yml
    templates: /var/lib/wazo-auth/templates
  clean:
    - /usr/local/bin/wazo-auth
    - /usr/local/bin/wazo-auth-init-db
    - /usr/local/bin/wazo-auth-bootstrap
    - /usr/local/bin/wazo-auth-wait

wazo-auth-cli:
  python3: true
  clean:
    - /usr/local/bin/wazo-auth-cli

wazo-auth-client:
  python2: true
  python3: true

wazo-auth-keys:
  python3: true
  clean:
    - /usr/local/bin/wazo-auth-keys
  bind:
    etc/wazo-auth-keys/config.yml: /etc/wazo-auth-keys/config.yml
    etc/wazo-auth/conf.d/50-wazo-default-policies.yml: /etc/wazo-auth/conf.d/50-wazo-default-policies.yml

wazo-debug:
  python3: true
  clean:
    - /usr/local/bin/wazo-debug

wazo-call-logd:
  python3: true
  clean:
    - /usr/local/bin/wazo-call-logd
    - /usr/local/bin/wazo-call-logd-init-db
    - /usr/local/bin/wazo-call-logd-upgrade-db
    - /usr/local/bin/wazo-call-logd-migrate-db
    - /usr/local/bin/wazo-call-logs

wazo-call-logd-client:
  python2: true
  python3: true

wazo-calld:
  python3: true
  bind:
    etc/wazo-calld/config.yml: /etc/wazo-calld/config.yml
  clean:
    - /usr/local/bin/wazo-calld

wazo-calld-client:
  python2: true
  python3: true

wazo-chatd:
  python3: true
  bind:
    etc/wazo-chatd/config.yml: /etc/wazo-chatd/config.yml
    alembic: /usr/share/wazo-chatd/alembic
  clean:
    - /usr/local/bin/wazo-chatd
    - /usr/local/bin/wazo-chatd-init-db

wazo-confd:
  python3: true
  bind:
    etc/wazo-confd/config.yml: /etc/wazo-confd/config.yml
  clean:
    - /usr/local/bin/wazo-confd
    - /usr/local/bin/wazo-confd-sync-db

wazo-confd-client:
  python2: true
  python3: true

wazo-confgend:
  python2: true
  bind:
    etc/wazo-confgend/config.yml: /etc/wazo-confgend/config.yml
    etc/wazo-confgend/templates: /etc/wazo-confgend/templates
  clean:
    - /usr/local/bin/wazo-confgend

wazo-confgend-client:
  bind:
    bin/wazo-confgen: /usr/bin/wazo-confgen

wazo-dird:
  python3: true
  bind:
    etc/wazo-dird/config.yml: /etc/wazo-dird/config.yml
    alembic: /usr/share/wazo-dird/alembic
  clean:
    - /usr/local/bin/wazo-dird

wazo-dird-client:
  python2: true
  python3: true

wazo-dxtora:
  python3: true
  bind:
    etc/wazo-dxtora/config.yml: /etc/wazo-dxtora/config.yml
  clean:
    - /usr/local/bin/wazo-dxtora

wazo-lib-rest-client:
  python2: true
  python3: true

wazo-libsccp:
  bind: []

wazo-phoned:
  python3: true
  bind:
    etc/wazo-phoned/config.yml: /etc/wazo-phoned/config.yml
  clean:
    - /usr/local/bin/wazo-phoned

wazo-plugind:
  python3: true
  bind:
    etc/wazo-plugind/config.yml: /etc/wazo-plugind/config.yml
  clean:
    - /usr/local/bin/wazo-plugind

wazo-plugind-cli:
  python3: true
  clean:
    - /usr/local/bin/wazo-plugind-cli

wazo-purge-db:
  python3: true
  bind:
    etc/wazo-purge-db/config.yml: /etc/wazo-purge-db/config.yml
  clean:
    - /usr/local/bin/wazo-purge-db

wazo-provd:
  python2: true
  bind:
    etc/wazo-provd: /etc/wazo-provd
  log_filename: /var/log/wazo-provd.log
  service: wazo-provd

wazo-provd-cli:
  python2: true
  clean:
    - /usr/local/bin/wazo-provd-cli

wazo-provd-client:
  python2: true
  python3: true

wazo-res-amqp:
  clean: []

wazo-service:
  python3: true
  bind:
    bin/wazo-service: /usr/bin/wazo-service
  clean:
    - /usr/local/bin/wazo-service-python

wazo-setupd:
  python3: true
  bind:
    etc/wazo-setupd/config.yml: /etc/wazo-setupd/config.yml
  clean:
    - /usr/local/bin/wazo-setupd

wazo-setupd-client:
  python3: true

wazo-stat:
  python3: true

wazo-ui:
  python3: true
  bind:
    etc/wazo-ui/config.yml: /etc/wazo-ui/config.yml
  clean:
    - /usr/local/bin/wazo-ui

wazo-upgrade:
  bind:
    post-start.d: /usr/share/wazo-upgrade/post-start.d
    post-stop.d: /usr/share/wazo-upgrade/post-stop.d
    pre-start.d: /usr/share/wazo-upgrade/pre-start.d
    pre-stop.d: /usr/share/wazo-upgrade/pre-stop.d
    etc/wazo-upgrade/config.yml: /etc/wazo-upgrade/config.yml
    bin/real-wazo-upgrade: /usr/bin/real-wazo-upgrade
    bin/wazo-upgrade: /usr/bin/wazo-upgrade
    bin/wazo-asterisk-custom-modules: /usr/bin/wazo-asterisk-custom-modules
    bin/wazo-check-conffiles: /usr/bin/wazo-check-conffiles

wazo-webhookd:
  python3: true
  bind:
    etc/wazo-webhookd/config.yml: /etc/wazo-webhookd/config.yml
    alembic: /usr/share/wazo-webhookd/alembic
  clean:
    - /usr/local/bin/wazo-webhookd
    - /usr/local/bin/wazo-webhookd-init-amqp
    - /usr/local/bin/wazo-webhookd-init-db

wazo-webhookd-client:
  python2: true
  python3: true

wazo-websocketd:
  python3: true
  bind:
    etc/wazo-websocketd/config.yml: /etc/wazo-websocketd/config.yml
  clean:
    - /usr/local/bin/wazo-websocketd

xivo-bus:
  python2: true
  python3: true

xivo-config:
  bind:
    dialplan: /usr/share/xivo-config/dialplan
    etc/xivo/asterisk/xivo_globals.conf: /etc/xivo/asterisk/xivo_globals.conf
    sbin/xivo-create-config: /usr/sbin/xivo-create-config
    sbin/xivo-read-config: /usr/sbin/xivo-read-config
    sbin/xivo-update-config: /usr/sbin/xivo-update-config
    templates: /usr/share/xivo-config/templates

xivo-dao:
  python2: true
  python3: true

xivo-lib-python:
  python2: true
  python3: true

xivo-manage-db:
  bind:
    bin/pg-drop-db: /usr/lib/xivo-manage-db/pg-drop-db
    bin/pg-populate-db: /usr/lib/xivo-manage-db/pg-populate-db
    alembic: /usr/share/xivo-manage-db/alembic

xivo-monitoring:
  bind:
    xivo-monitoring-update: /usr/sbin/xivo-monitoring-update

xivo-swagger-doc:
  bind:
    index.json: /usr/share/xivo-swagger-doc/catalog/index.json

wazo-sysconfd:
  python2: true

xivo-utils:
  bind:
    sbin/wazo-reset: /usr/sbin/wazo-reset
